<h2>¿Qué es GyPI?</h2><br>
<p>Es un sistema que ayudará a gestionar los proyectos ya aceptados de los grupos de investigación permitiendo a las instancias administrativas de la Universidad de Antioquia centralizar la información de los diferentes grupos de investigación propiciando su acceso a la comunidad universitaria y al público en general.</p>
<p>GyPI permite registrar proyectos de investigación ya aprobados previamente, ingresando a cada uno de ellos los datos mas relevantes tales como (nombre, compromisos, cronograma, entre otros), de esta manera se logra tener un registro organizado y manejable sobre los proyectos que actualmente están siendo desarrollados en la Universidad. A demás de esto el sistema facilita a los  integrantes de un grupo de investigación le manejo de los compromisos y trámites tales como seguimiento a los compromisos necesarios para la culminación de un proyecto de investigación, solicitudes de prórrogas y cambios de investigador e informes sobre cambios relavantes en el proyecto al cual se encuentrénm vinculados.</p>

Integrantes:<br>
- Alejandro Palacio Duque<br>
- Sigifredo Escobar Gómez<br>
