
Solicitud de prórroga guardada satisfactoriamente.<br>
<br>
Número de identificación: <span class="respuesta">####</span><br>
<br>
Proyecto: <span class="respuesta"><?php echo $_POST["proyecto"]; ?></span><br>
<br>
Nueva fecha: <span class="respuesta"><?php echo $_POST["fecha"]; ?></span><br>
<br>
Justificación:<br>
<span class="respuesta"><?php echo $_POST["justificacion"]; ?></span><br>
<br>
Archivo: <span class="respuesta"><?php echo $_POST["archivo"]; ?></span><br>
