
<h2>Prórroga</h2>

<form method="post" action="<?php echo $this->url(array("controller" => "prorroga", "action" => "guardar"));  ?>">

Proyecto: <input name="proyecto" type="text" /><br>
<br>
Nueva fecha: <input name="fecha" type="date" /><br>
<br>
Justificación:<br>
<textarea name="justificacion" rows="10" cols="50"></textarea><br>
<br>
Adjuntar archivo:<br>
<input name="archivo" type="file" />
<br><br>
<input type="submit" value="Guardar" />
<input type="reset" value="Restaurar" />

</form>
