
Solicitud de cambio de invesigador guardada satisfactoriamente.<br>
<br>
Número de identificación: <span class="respuesta">####</span><br>
<br>
Proyecto: <span class="respuesta"><?php echo $_POST["proyecto"]; ?></span><br>
<br>
Responsable: <span class="respuesta"><?php echo $_POST["responsable"]; ?></span><br>
<br>
Jutificación:<br>
<span class="respuesta"><?php echo $_POST["justificacion"]; ?></span><br>
<br>
Perfil del nuevo investigador:<br>
<span class="respuesta"><?php echo $_POST["perfil"]; ?></span><br>
<br>
Archivo: <span class="respuesta"><?php echo $_POST["archivo"]; ?></span><br>
