<?php
echo $this->doctype("HTML5");
?>
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <?php
    echo $this->headMeta();
    echo $this->headScript();
    echo $this->headLink()->appendStylesheet($this->baseUrl().'/global.css');
    echo $this->headLink(array('rel' => 'icon', 'href' => $this->baseUrl().'/img/favicon.png','type' => 'image/x-icon'));
    $this->headTitle()->prepend('GyPI - ');
    echo $this->headTitle();
  ?>
    <script src="<?php echo $this->baseUrl(); ?>/jquery-1.7.1.min.js"></script>
    <script src="<?php echo $this->baseUrl(); ?>/main.js"></script>
  </head>
  <body>
    <header id="hdppal">GyPI</header>
    <div id="center">
    <ul id="menu">
      <li>Registro</li>
      <li><a id="solicitudes" href="#">Solicitudes</a></li>
      <ul id="lssolicitudes" class="submenu">
        <li><a href="<?php echo $this->url(array("controller" => "cinvestigador", "action" => "index"));  ?>">- Cambio de investigador</a></li>
        <li><a href="<?php echo $this->url(array("controller" => "prorroga", "action" => "index")); ?>">- Prórroga</a></li>
        <li><a href="<?php echo $this->url(array("controller" => "responder", "action" => "index")); ?>">- Responder solicitud</a></li>
      </ul>
      <li><a href="<?php echo $this->url(array("controller" => "buscar", "action" => "index")); ?>">Buscar</a></li>
    </ul>
    <div id="content"><?php echo $this->layout()->content; ?>
    </div>
    <div class="clear"></div></div>
    <footer id="ftppal">Copyright © 2011 GfifDev S.A.S. Todos los derechos reservados.</footer>
  </body>
</html>
