<?php
echo $this->doctype("HTML5");
?>
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <?php
    echo $this->headMeta();
    echo $this->headScript();
    echo $this->headLink()->appendStylesheet($this->baseUrl().'/global.css');
    $this->headTitle()->prepend('GyPI - ');
    echo $this->headTitle();
  ?>
    <script src="<?php echo $this->baseUrl(); ?>/jquery-1.7.1.min.js"></script>
    <script src="<?php echo $this->baseUrl(); ?>/main.js"></script>
  </head>
  <body>
    <header id="hdppal">GyPI</header>
    <div id="center">
    <div id="menu">
      <a id="inicio" href="<?php echo $this->url(array("controller" => "index", "action" => "index")); ?>">Inicio</a><br><br>
      <a id="reg-proy" href="<?php echo $this->url(array("controller" => "reg-proy", "action" => "index")); ?>">Registro de proyecto</a><br><br>
      <a id="solicitudes" href="#">Solicitudes</a><br><br>
      <div id="lssolicitudes" class="submenu">
        <a href="<?php echo $this->url(array("controller" => "cinvestigador", "action" => "index"));  ?>"> - Cambio de investigador</a><br><br>
        <a href="<?php echo $this->url(array("controller" => "prorroga", "action" => "index")); ?>"> - Prórroga</a><br><br>
        <a href="<?php echo $this->url(array("controller" => "responder", "action" => "index")); ?>"> - Responder solicitud</a><br><br>
      </div>
      <a href="<?php echo $this->url(array("controller" => "buscar", "action" => "index")); ?>">Buscar</a><br><br>
    </div>
    <div id="content"><?php echo $this->layout()->content; ?>
    </div>
    <div class="clear"></div></div>
    <footer id="ftppal">GyPI - 2011/12</footer>
  </body>
</html>
