<br>
Prórrogas del proyecto <?php echo $this->id; ?>:<br>
<br>
<a href="<?php echo $this->url(array("controller" => "buscar", "action" => "prorroga", "id" => "3121")); ?>">prórroga 3121</a><br>
<a href="<?php echo $this->url(array("controller" => "buscar", "action" => "prorroga", "id" => "4123")); ?>">prórroga 4123<br>
<a href="<?php echo $this->url(array("controller" => "buscar", "action" => "prorroga", "id" => "5122")); ?>">prórroga 5122<br>
<a href="<?php echo $this->url(array("controller" => "buscar", "action" => "prorroga", "id" => "7133")); ?>">prórroga 7133<br>
