
Búsquedas<br>
<br>
Proyectos:<br>
<br>
<a href="<?php echo $this->url(array("controller" => "buscar", "action" => "proyecto", "id" => "1")); ?>">proyecto 1</a><br>
<a href="<?php echo $this->url(array("controller" => "buscar", "action" => "proyecto", "id" => "2")); ?>">proyecto 2</a><br>
<a href="<?php echo $this->url(array("controller" => "buscar", "action" => "proyecto", "id" => "3")); ?>">proyecto 3</a><br>
<a href="<?php echo $this->url(array("controller" => "buscar", "action" => "proyecto", "id" => "4")); ?>">proyecto 4</a><br>
<a href="<?php echo $this->url(array("controller" => "buscar", "action" => "proyecto", "id" => "5")); ?>">proyecto 5</a><br>
<a href="<?php echo $this->url(array("controller" => "buscar", "action" => "proyecto", "id" => "6")); ?>">proyecto 6</a><br>
